# Generated by Django 5.1.1 on 2024-10-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='api.seccion'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
